# Generated by Django 3.2.14 on 2022-10-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('transact_type', models.CharField(max_length=8)),
                ('currency', models.CharField(max_length=10)),
                ('net', models.FloatField()),
                ('vat', models.FloatField()),
            ],
        ),
    ]
